// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjIt_M6nP-VBNhLvfFU77Qq_FxhCiT2DI',
    appId: '1:501207645776:web:872c088fcbf97e9dbc9b55',
    messagingSenderId: '501207645776',
    projectId: 'geoquiz-c6668',
    authDomain: 'geoquiz-c6668.firebaseapp.com',
    storageBucket: 'geoquiz-c6668.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2FQ3rUyr5Ndex7hLos1kxtuTeSrYm64',
    appId: '1:501207645776:android:2ad0acd732f6bb6dbc9b55',
    messagingSenderId: '501207645776',
    projectId: 'geoquiz-c6668',
    storageBucket: 'geoquiz-c6668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_5Rz1hTojNQRyxaHsiORlIYOfGzYepQ8',
    appId: '1:501207645776:ios:b02e45350662e1a2bc9b55',
    messagingSenderId: '501207645776',
    projectId: 'geoquiz-c6668',
    storageBucket: 'geoquiz-c6668.appspot.com',
    androidClientId: '501207645776-15s0cv54m1snmqkrm38sgvoc2faag00n.apps.googleusercontent.com',
    iosClientId: '501207645776-3lr7tbkqtoe7pk1a19057dmilat6pcma.apps.googleusercontent.com',
    iosBundleId: 'no.ntnu.geoquiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_5Rz1hTojNQRyxaHsiORlIYOfGzYepQ8',
    appId: '1:501207645776:ios:b02e45350662e1a2bc9b55',
    messagingSenderId: '501207645776',
    projectId: 'geoquiz-c6668',
    storageBucket: 'geoquiz-c6668.appspot.com',
    androidClientId: '501207645776-15s0cv54m1snmqkrm38sgvoc2faag00n.apps.googleusercontent.com',
    iosClientId: '501207645776-3lr7tbkqtoe7pk1a19057dmilat6pcma.apps.googleusercontent.com',
    iosBundleId: 'no.ntnu.geoquiz',
  );
}
